[git] Updated precommit hook

diff --git a/githooks/pre-commit b/githooks/pre-commit
--- a/githooks/pre-commit
+++ b/githooks/pre-commit
@@ -1,16 +1,35 @@
 #!/bin/sh
 
-STYLE=$(git config --get hooks.clangformat.style)
-if [ -n "${STYLE}" ] ; then
-  STYLEARG="-style=${STYLE}"
+BINARY=$(git config --get clangformat.binary)
+if [ -n "${BINARY}" ] ; then
+  BINARY_ARG="${BINARY}"
 else
-  STYLEARG=""
+  BINARY_ARG='C:/Program Files/LLVM/bin/clang-format.exe'
 fi
+
+STYLE=$(git config --get clangformat.style)
+if [ -n "${STYLE}" ] ; then
+  STYLE_ARG="--style=${STYLE}"
+else
+  STYLE_ARG='--style=file'
+fi
+
+EXTENSIONS=$(git config --get clangformat.extensions)
+if [ -n "${EXTENSIONS}" ] ; then
+  EXTENSIONS_ARG="${EXTENSIONS}"
+else
+  EXTENSIONS_ARG='c,cpp,h,hpp'
+fi
+
+EXTENSIONS_ARG=`echo ${EXTENSIONS_ARG} | sed -r 's/,/|/g'`
 
 format_file() {
   file="${1}"
   if [ -f $file ]; then
-    "C:\\Program Files\\LLVM\\bin\\clang-format.exe" -i ${STYLEARG} ${1}
+    if ! `"${BINARY_ARG}" -i ${STYLEARG} ${1}`; then
+        echo "clang-format failed"
+        exit 1
+    fi
     git add ${1}
   fi
 }
@@ -20,7 +39,7 @@ case "${1}" in
     echo "Runs clang-format on source files"
     ;;
   * )
-    for file in `git diff-index --cached --name-only HEAD | grep -iE '\.(cpp|cc|h|hpp)$' ` ; do
+    for file in `git diff-index --cached --name-only HEAD | grep -iE "\.(${EXTENSIONS_ARG})$"` ; do
       format_file "${file}"
     done
     ;;
